name: tests

on:
  push:
  pull_request:
    branches:
    - master
    - dev

jobs:
  test:
    name: Build & run tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.6']
    steps:
      - name: Setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: qfit
      - name: Conda info
        shell: bash -l -eo pipefail {0}
        run: conda info
      - name: Conda create environment
        shell: bash -l -eo pipefail {0}
        run: |
          conda install -c ibmdecisionoptimization cplex
          conda install -c anaconda mkl numpy scipy
      - name: Checkout qfit
        uses: actions/checkout@v2
      - name: Install package
        working-directory: .
        shell: bash -l -eo pipefail {0}
        run: pip install .
      - name: Describe qfit environment
        shell: bash -l -eo pipefail {0}
        run: conda list
      - name: Check qfit_protein help
        shell: bash -l {0}
        run: qfit_protein --help
