name: tests

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  test:
    name: Build & run tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.6']
    steps:
      - name: Setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: qfit
      - name: Conda info
        shell: bash -l -eo pipefail {0}
        run: conda info
      - name: Build conda environment
        shell: bash -l -eo pipefail {0}
        run: |
          # Set up channel priority
          conda config --prepend channels conda-forge && \
          conda config --prepend channels anaconda
          # Set strict adherence to channels
          conda update --strict-channel-priority --all
          # Read channels priority
          conda config --show channels
          # Install tox-conda (testing automator)
            # For now, we must use the master branch until a new release is made (> v0.2.1).
            # https://github.com/tox-dev/tox-conda/issues/40
            # conda install --yes tox-conda
          pip install git+git://github.com/tox-dev/tox-conda.git
      - name: Checkout qfit
        uses: actions/checkout@v2
      - name: Install qfit
        working-directory: .
        shell: bash -l -eo pipefail {0}
        run: pip install .
      - name: Describe qfit environment
        shell: bash -l -eo pipefail {0}
        run: conda list
      - name: TEST (Basic) Check qfit_protein can execute (test --help)
        shell: bash -l {0}
        run: qfit_protein --help
      - name: TEST (Full) Thoroughly test qFit with tox
        shell: bash -l {0}
        run: tox
