name: tests

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  test:
    name: Build & run tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.6']
    steps:
      - uses: actions/checkout@v2
      #- name: Setup Conda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          #auto-update-conda: true
          channels: anaconda,ibmdecisionoptimization
          auto-activate-base: false
          #miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: env.yml
          activate-environment: qfit
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run pytest with the Conda environment
        shell: bash -l {0}
        run: |
          pip install .
          #pip install tox-conda
          #conda install --yes tox-conda
          conda install pytest
          #$CONDA/bin/pytest
          pytest
