name: tests

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  test:
    name: Build & run tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.6']
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Update Conda environment with environment.yml
        uses: actions/checkout@v1
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          #activate-enironment: qfit
          #environment-file: environment.yml
        shell: bash -l {0}
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
          conda install pytest
          conda info
          conda list
      - name: Run pytest with the Conda environment
        shell: bash -l {0}
        run: pytest
