name: tests

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  test:
    name: Build & run tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.6']
        exclude:
          # Sidestep the issue: (this problem appears to be with the runner).
          #   conda can't install vs2015_runtime-14.16, can't build env
          #   TO BE REMOVED LATER.
          - os: windows-latest
            python-version: '3.7'
    steps:
      - name: Setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: qfit
      - name: Conda info
        shell: bash -l -eo pipefail {0}
        run: conda info
      - name: Build conda environment
        shell: bash -l -eo pipefail {0}
        run: |
          # Set up channel priority
          conda config --prepend channels conda-forge && \
          conda config --prepend channels anaconda
          # Read channels priority
          conda config --show channels
          # Install tox (testing automator)
          conda install --yes tox-conda
      - name: Checkout qfit
        uses: actions/checkout@v2
      - name: Install qfit
        working-directory: .
        shell: bash -l -eo pipefail {0}
        run: pip install .
      - name: Describe qfit environment
        shell: bash -l -eo pipefail {0}
        run: conda list
      - name: TEST (Basic) Check qfit_protein can execute (test --help)
        shell: bash -l {0}
        run: qfit_protein --help
      - name: TEST (Full) Thoroughly test qFit with tox
        shell: bash -l {0}
        run: tox
